name: Atoum's website
#highlighter: rouge
timezone: Europe/Paris
future: true
exclude:
  - docker-compose.yml
  - vendor
  - scripts

markdown: kramdown
kramdown:
    parse_block_html: true
    parse_span_html: true

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-sitemap
  - jekyll-feed

feed:
  path: atom.xml

jekyll-mentions:
  base_url: https://github.com

ga:
  tracking: UA-72192129-1
